### ISSUE TITLE
Test the system by different users

### ISSUE THREAD

**Issue by IGragon** [InnoSWP/05-DocPdf-Converter#19]
- Comment what is good and what is not
- Describe features that you want to add in project (if any)

**Comment by zaqbez39me** [comment]
I tested the project on my PC and found that project works well. It seems that the only one flaw of our API is that it does not send single files without archiving. I suppose this feature should be added.

**Comment by osx11** [comment]
Conducted manual tests of API and frontend interface showed that the program works fine, and the speed of conversion is acceptable. There are no artifacts after conversion on the files that I used for testing.

**Required features**: I agree with @zaqbez39me that the single file should not be archived after conversion.

**Disadvantages**: Frontend is not adaptive.
_Note_: frontend is not adaptive since the converter is designed to be used only as an API from another backend, and it is not planned to be used on mobile devices. Also, I emphasize that the interface is only used as a demo for a presentation, and it is not planned to be used in future.

**Comment by IGragon** [comment]
Everything works as it should. Nothing to add to my teammates comments

**Comment by zaqbez39me** [comment]
Tested by 3 team members, can be closed.

**Comment by SanikoZmey** [comment]
Aproximately 14 files were converted by the programm and in 2-3 of them several minor issues were detected. Seems that there are no ways to somehow improve the quality of convertion without writing writing the whole convertion algorithm from nothing. It will require much longer time resources, but the in the result we will get pretty the same product(in terms of quality), but with some "bonus" features.

**Comment by zaqbez39me** [comment]
For this moment, 4 team members tested our system. This issue can be closed.
